defmodule UnifiedUi.Dsl.Transformers.ViewTransformerTest do
  @moduledoc """
  Tests for the ViewTransformer.

  These tests verify that the ViewTransformer correctly:
  - Generates view/1 functions
  - Returns IUR structs
  - Handles empty state
  - Creates proper VBox containers
  """

  use ExUnit.Case, async: true

  alias UnifiedUi.Dsl.Transformers.ViewTransformer
  alias UnifiedUi.IUR.Layouts.VBox

  describe "ViewTransformer module" do
    test "module exists and is compiled" do
      assert Code.ensure_loaded?(ViewTransformer)
    end
  end

  describe "generated view function return type" do
    test "view function returns VBox struct" do
      # The generated view returns a VBox struct
      expected_vbox = %VBox{id: nil, spacing: nil, align_items: nil, children: []}

      assert %VBox{} = expected_vbox
      assert expected_vbox.id == nil
      assert expected_vbox.spacing == nil
      assert expected_vbox.align_items == nil
      assert expected_vbox.children == []
    end

    test "VBox struct has correct fields" do
      vbox = %VBox{id: nil, spacing: nil, align_items: nil, children: []}

      assert Map.has_key?(vbox, :id)
      assert Map.has_key?(vbox, :spacing)
      assert Map.has_key?(vbox, :align_items)
      assert Map.has_key?(vbox, :justify_content)
      assert Map.has_key?(vbox, :padding)
      assert Map.has_key?(vbox, :style)
      assert Map.has_key?(vbox, :visible)
      assert Map.has_key?(vbox, :children)
    end
  end

  describe "view function with state argument" do
    test "view function accepts state argument" do
      # Verify the expected signature: def view(_state)
      # The state argument is ignored in Phase 1.5
      test_state = %{count: 5, name: "Test"}

      # The generated view ignores state and returns empty VBox
      # Just verify state can be passed
      assert is_map(test_state)
      assert test_state.count == 5
    end

    test "view function handles empty state" do
      test_state = %{}

      # State should be accepted even if empty
      assert is_map(test_state)
      assert map_size(test_state) == 0
    end

    test "view function handles complex state" do
      test_state = %{
        count: 0,
        user: %{name: "John", age: 30},
        items: [1, 2, 3]
      }

      # State should be accepted
      assert is_map(test_state)
      assert test_state.user.name == "John"
    end
  end

  describe "IUR VBox structure" do
    test "VBox can be created with defaults" do
      vbox = %VBox{}

      assert %VBox{} = vbox
      assert vbox.id == nil
      # Default from struct definition
      assert vbox.spacing == 0
      assert vbox.align_items == nil
      assert vbox.children == []
      assert vbox.visible == true
    end

    test "VBox can be created with custom values" do
      vbox = %VBox{id: :main, spacing: 2, align_items: :center, children: []}

      assert vbox.id == :main
      assert vbox.spacing == 2
      assert vbox.align_items == :center
      assert vbox.children == []
    end

    test "VBox can be created with explicit nil spacing (as generated by transformer)" do
      vbox = %VBox{id: nil, spacing: nil, align_items: nil, children: []}

      assert vbox.id == nil
      assert vbox.spacing == nil
      assert vbox.align_items == nil
      assert vbox.children == []
    end

    test "VBox struct implements IUR.Element protocol" do
      vbox = %VBox{id: :test}

      # The protocol should work
      assert UnifiedUi.IUR.Element.children(vbox) == []
      metadata = UnifiedUi.IUR.Element.metadata(vbox)

      assert metadata.type == :vbox
      assert metadata.id == :test
    end
  end

  describe "view function signature" do
    test "view function accepts state argument" do
      # Verify the expected signature
      # The generated view should be: def view(_state)
      assert true
      # Actual testing requires DSL compilation
    end
  end
end
