defmodule Mix.Tasks.UnifiedUi.Gen.Widget do
  @shortdoc "Generates custom widget boilerplate with UnifiedIUR.Element support"
  @moduledoc """
  Generates a custom widget module and optional test scaffold.

  The generated widget includes:

  - a struct with common widget fields (`id`, `style`, `visible`)
  - a `UnifiedIUR.Element` protocol implementation
  - typed metadata helper for renderers

  ## Usage

      mix unified_ui.gen.widget MyApp.Widgets.StatusBadge

  ## Options

  - `--path` - output path for the generated module (directory or `.ex` file path)
  - `--test-path` - output path for generated test (directory or `_test.exs` file path)
  - `--no-test` - skip test generation
  - `--force` - overwrite existing generated files
  """
  use Mix.Task

  @switches [path: :string, test_path: :string, no_test: :boolean, force: :boolean]

  @impl Mix.Task
  @spec run([String.t()]) :: :ok
  def run(args) do
    run_with(args, fn line -> Mix.shell().info(line) end)
  end

  @doc false
  @spec run_with([String.t()], (String.t() -> any())) :: :ok
  def run_with(args, output_fun) when is_function(output_fun, 1) do
    {opts, positional, invalid} = OptionParser.parse(args, strict: @switches)

    case invalid do
      [] ->
        :ok

      invalid_opts ->
        raise Mix.Error,
          message:
            "Unsupported options for mix unified_ui.gen.widget: #{inspect(invalid_opts)}. " <>
              "Supported options: --path, --test-path, --no-test, --force."
    end

    module_name =
      case positional do
        [name] ->
          validate_module_name!(name)

        [] ->
          raise Mix.Error,
            message:
              "Missing module name. Usage: mix unified_ui.gen.widget MyApp.Widgets.Badge [options]"

        _extra ->
          raise Mix.Error,
            message:
              "Expected exactly one module name. Usage: mix unified_ui.gen.widget MyApp.Widgets.Badge [options]"
      end

    module_file = module_file_path(module_name, opts[:path])
    test_file = test_file_path(module_name, opts[:test_path])
    force? = !!opts[:force]

    write_file!(module_file, widget_template(module_name), force?)
    output_fun.("Created widget: #{module_file}")

    unless opts[:no_test] do
      write_file!(test_file, widget_test_template(module_name), force?)
      output_fun.("Created test: #{test_file}")
    end

    :ok
  end

  defp validate_module_name!(name) do
    if Regex.match?(~r/^[A-Z]\w*(\.[A-Z]\w*)*$/, name) do
      name
    else
      raise Mix.Error,
        message:
          "Invalid module name: #{inspect(name)}. Expected alias format like MyApp.Widgets.Badge."
    end
  end

  defp module_file_path(module_name, nil) do
    module_name
    |> Macro.underscore()
    |> then(&Path.join("lib", "#{&1}.ex"))
  end

  defp module_file_path(module_name, path) do
    if String.ends_with?(path, ".ex") do
      path
    else
      module_basename = module_name |> module_basename() |> Kernel.<>(".ex")
      Path.join(path, module_basename)
    end
  end

  defp test_file_path(module_name, nil) do
    module_name
    |> Macro.underscore()
    |> then(&Path.join("test", "#{&1}_test.exs"))
  end

  defp test_file_path(module_name, path) do
    if String.ends_with?(path, "_test.exs") do
      path
    else
      module_basename = module_name |> module_basename() |> Kernel.<>("_test.exs")
      Path.join(path, module_basename)
    end
  end

  defp module_basename(module_name) do
    module_name
    |> String.split(".")
    |> List.last()
    |> Macro.underscore()
  end

  defp module_alias_basename(module_name) do
    module_name
    |> String.split(".")
    |> List.last()
  end

  defp widget_type_atom(module_name) do
    module_name
    |> module_basename()
    |> String.to_atom()
  end

  defp write_file!(path, contents, force?) do
    case {File.exists?(path), force?} do
      {true, false} ->
        raise Mix.Error,
          message: "File already exists: #{path}. Use --force to overwrite."

      _ ->
        path |> Path.dirname() |> File.mkdir_p!()
        File.write!(path, contents)
    end
  end

  defp widget_template(module_name) do
    type_atom = widget_type_atom(module_name)

    """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      Custom widget scaffold generated by `mix unified_ui.gen.widget`.
      \"\"\"

      defstruct [:id, :label, :value, :style, visible: true]

      @type t :: %__MODULE__{
              id: atom() | nil,
              label: String.t() | nil,
              value: term(),
              style: UnifiedIUR.Style.t() | nil,
              visible: boolean()
            }
    end

    defimpl UnifiedIUR.Element, for: #{module_name} do
      @doc false
      def children(_widget), do: []

      @doc false
      def metadata(widget) do
        %{
          type: :#{type_atom},
          id: widget.id,
          label: widget.label,
          value: widget.value,
          visible: widget.visible,
          style: widget.style
        }
      end
    end
    """
  end

  defp widget_test_template(module_name) do
    alias_basename = module_alias_basename(module_name)
    type_atom = widget_type_atom(module_name)

    """
    defmodule #{module_name}Test do
      use ExUnit.Case, async: true

      alias #{module_name}

      test "implements UnifiedIUR.Element protocol" do
        widget = %#{alias_basename}{id: :sample, label: "Sample", value: 42}

        assert [] = UnifiedIUR.Element.children(widget)

        assert %{type: :#{type_atom}, id: :sample, label: "Sample", value: 42} =
                 UnifiedIUR.Element.metadata(widget)
      end
    end
    """
  end
end
