defmodule Mix.Tasks.UnifiedUi.Gen.Extension do
  @shortdoc "Generates extension boilerplate (widget + renderer scaffold)"
  @moduledoc """
  Generates a UnifiedUi extension module with custom widget and renderer scaffolding.

  The generated extension includes:

  - a root extension module with a `components/0` helper
  - a custom `Widgets.StatusBadge` module
  - a `UnifiedIUR.Element` implementation for the custom widget
  - a custom `Renderers.Terminal` module implementing `UnifiedUi.Renderer`
  - an optional test module

  ## Usage

      mix unified_ui.gen.extension MyApp.Extensions.Observability

  ## Options

  - `--path` - output path for the generated module (directory or `.ex` file path)
  - `--test-path` - output path for generated test (directory or `_test.exs` file path)
  - `--no-test` - skip test generation
  - `--force` - overwrite existing generated files
  """
  use Mix.Task

  @switches [path: :string, test_path: :string, no_test: :boolean, force: :boolean]

  @impl Mix.Task
  @spec run([String.t()]) :: :ok
  def run(args) do
    run_with(args, fn line -> Mix.shell().info(line) end)
  end

  @doc false
  @spec run_with([String.t()], (String.t() -> any())) :: :ok
  def run_with(args, output_fun) when is_function(output_fun, 1) do
    {opts, positional, invalid} = OptionParser.parse(args, strict: @switches)

    case invalid do
      [] ->
        :ok

      invalid_opts ->
        raise Mix.Error,
          message:
            "Unsupported options for mix unified_ui.gen.extension: #{inspect(invalid_opts)}. " <>
              "Supported options: --path, --test-path, --no-test, --force."
    end

    module_name =
      case positional do
        [name] ->
          validate_module_name!(name)

        [] ->
          raise Mix.Error,
            message:
              "Missing module name. Usage: mix unified_ui.gen.extension MyApp.Extensions.MyExtension [options]"

        _extra ->
          raise Mix.Error,
            message:
              "Expected exactly one module name. Usage: mix unified_ui.gen.extension MyApp.Extensions.MyExtension [options]"
      end

    module_file = module_file_path(module_name, opts[:path])
    test_file = test_file_path(module_name, opts[:test_path])
    force? = !!opts[:force]

    write_file!(module_file, extension_template(module_name), force?)
    output_fun.("Created extension: #{module_file}")

    unless opts[:no_test] do
      write_file!(test_file, extension_test_template(module_name), force?)
      output_fun.("Created test: #{test_file}")
    end

    :ok
  end

  defp validate_module_name!(name) do
    if Regex.match?(~r/^[A-Z]\w*(\.[A-Z]\w*)*$/, name) do
      name
    else
      raise Mix.Error,
        message:
          "Invalid module name: #{inspect(name)}. Expected alias format like MyApp.Extensions.Observability."
    end
  end

  defp module_file_path(module_name, nil) do
    module_name
    |> Macro.underscore()
    |> then(&Path.join("lib", "#{&1}.ex"))
  end

  defp module_file_path(module_name, path) do
    if String.ends_with?(path, ".ex") do
      path
    else
      module_basename = module_name |> module_basename() |> Kernel.<>(".ex")
      Path.join(path, module_basename)
    end
  end

  defp test_file_path(module_name, nil) do
    module_name
    |> Macro.underscore()
    |> then(&Path.join("test", "#{&1}_test.exs"))
  end

  defp test_file_path(module_name, path) do
    if String.ends_with?(path, "_test.exs") do
      path
    else
      module_basename = module_name |> module_basename() |> Kernel.<>("_test.exs")
      Path.join(path, module_basename)
    end
  end

  defp module_basename(module_name) do
    module_name
    |> String.split(".")
    |> List.last()
    |> Macro.underscore()
  end

  defp module_alias_basename(module_name) do
    module_name
    |> String.split(".")
    |> List.last()
  end

  defp widget_type_atom(module_name) do
    module_name
    |> module_basename()
    |> Kernel.<>("_status_badge")
    |> String.to_atom()
  end

  defp write_file!(path, contents, force?) do
    case {File.exists?(path), force?} do
      {true, false} ->
        raise Mix.Error,
          message: "File already exists: #{path}. Use --force to overwrite."

      _ ->
        path |> Path.dirname() |> File.mkdir_p!()
        File.write!(path, contents)
    end
  end

  defp extension_template(module_name) do
    widget_type = widget_type_atom(module_name)

    """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      Extension scaffold generated by `mix unified_ui.gen.extension`.

      This scaffold includes:
      - `Widgets.StatusBadge` custom widget module
      - `Renderers.Terminal` custom renderer module
      \"\"\"

      alias __MODULE__.Renderers
      alias __MODULE__.Widgets

      @doc \"\"\"
      Returns modules exposed by this extension scaffold.
      \"\"\"
      @spec components() :: %{widget: module(), renderer: module()}
      def components do
        %{widget: Widgets.StatusBadge, renderer: Renderers.Terminal}
      end

      defmodule Widgets.StatusBadge do
        @moduledoc \"\"\"
        Example custom widget generated for the extension scaffold.
        \"\"\"

        defstruct [:id, :label, :value, :style, visible: true]

        @type t :: %__MODULE__{
                id: atom() | nil,
                label: String.t() | nil,
                value: term(),
                style: UnifiedIUR.Style.t() | nil,
                visible: boolean()
              }
      end

      defimpl UnifiedIUR.Element, for: #{module_name}.Widgets.StatusBadge do
        @doc false
        def children(_widget), do: []

        @doc false
        def metadata(widget) do
          %{
            type: :#{widget_type},
            id: widget.id,
            label: widget.label,
            value: widget.value,
            visible: widget.visible,
            style: widget.style
          }
        end
      end

      defmodule Renderers.Terminal do
        @moduledoc \"\"\"
        Example custom renderer generated for the extension scaffold.
        \"\"\"

        @behaviour UnifiedUi.Renderer

        alias #{module_name}.Widgets.StatusBadge
        alias UnifiedIUR.Widgets
        alias UnifiedUi.Adapters.State
        alias UnifiedUi.Adapters.Terminal, as: BaseTerminal

        @impl true
        def render(iur_tree, opts \\\\ []) do
          renderer_state = State.new(:terminal, config: opts)
          root = convert_iur(iur_tree)

          {:ok,
           renderer_state
           |> State.put_root(root)
           |> State.put_metadata(:last_iur, iur_tree)}
        end

        @impl true
        def update(iur_tree, renderer_state, _opts \\\\ []) do
          if State.get_metadata(renderer_state, :last_iur) == iur_tree do
            {:ok, renderer_state}
          else
            {:ok,
             renderer_state
             |> State.put_root(convert_iur(iur_tree))
             |> State.put_metadata(:last_iur, iur_tree)
             |> State.bump_version()}
          end
        end

        @impl true
        def destroy(_renderer_state), do: :ok

        defp convert_iur(%StatusBadge{label: label, value: value}) do
          %Widgets.Text{content: "\#{label}: \#{inspect(value)}"}
          |> BaseTerminal.convert_iur()
        end

        defp convert_iur(other), do: BaseTerminal.convert_iur(other)
      end
    end
    """
  end

  defp extension_test_template(module_name) do
    alias_basename = module_alias_basename(module_name)
    widget_type = widget_type_atom(module_name)

    """
    defmodule #{module_name}Test do
      use ExUnit.Case, async: true

      alias #{module_name}
      alias #{module_name}.Renderers.Terminal
      alias #{module_name}.Widgets.StatusBadge

      test "components/0 returns generated widget and renderer modules" do
        assert %{widget: StatusBadge, renderer: Terminal} = #{alias_basename}.components()
      end

      test "generated widget implements UnifiedIUR.Element protocol" do
        widget = %StatusBadge{id: :sample, label: "Sample", value: :ok}

        assert [] = UnifiedIUR.Element.children(widget)
        assert %{type: :#{widget_type}, id: :sample, label: "Sample", value: :ok} =
                 UnifiedIUR.Element.metadata(widget)
      end
    end
    """
  end
end
